### ISSUE TITLE
[css-typed-om] Should StyleMap be case sensitive?

### ISSUE THREAD

**Issue by esprehn** [w3c/css-houdini-drafts#309] opened 2016-09-22 10:28 UTC
Some folks want us to make the platform more case sensitive. Since this is a new API, that means we would make it case sensitive. ex.

``` js
element.styleMap.get("background-color") // works.
element.styleMap.get("Background-Color") // doesn't work.
```

Unfortunately this also diverges from `.style`, ex.

``` js
element.style.getPropertyValue("Color") // works.
element.style.getPropertyValue("COLOR") // works.
```

@annevk @domenic @foolip @tabatkins

**Comment by foolip** [comment] 2016-09-22 12:18
If I'm reading Blink's CSSPropertyParser.cpp correctly, `element.style.getPropertyValue` is always case sensitive, unlike e.g. `element.getAttribute` it doesn't depend on the document type. Presumably this code path could be reused if the new API is also case insensitive, where otherwise a new code path specifically to make the wrong case not work?

I'l defer to the people working on style in Blink. @wilddamon @rune-opera

**Comment by wilddamon** [comment] 2016-09-23 01:13
I was looking at this recently when I was trying to consolidate the various ways of parsing names we have in Blink. style.getPropertyValue isn't case sensitive - you can see the call to toASCIILower for each character [here](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/css/parser/CSSPropertyParser.cpp?&l=181) (I also tried in dev tools, `$0.style.getPropertyValue('wiDth')` definitely works).

So I think we'd have to create a new code path to do this.

**Comment by annevk** [comment] 2016-09-23 06:27
Would it be a completely new code path? Presumably the existing callers could ASCII lowercase early and from that point on you could have shared code. We've even thought of making the ASCII lowercase operation part of IDL since there are some other APIs where we could also use that kind of thing (all mostly for legacy reasons). (Unfortunately I don't recall which APIs at the moment.)

**Comment by foolip** [comment] 2016-09-23 08:28
@wilddamon, oops, I typo'd above, I meant case *insensitive* of course.

FWIW, in the context of lowercasing in `element.getAttribute` and friends (which are now case insensitive compares in Blink, observably different when the stored attributes aren't lowercase) I have entertained the option of putting an "is-ASCII-lowercase" flag on the atomic string type that's set when returned from a `toASCIILower` operation, so that attempting to lowercase it again is a no-op. Without some tricks like that I'd worry about perf regressions from always (actually) lowercasing the input, but then I stopped working on the attribute stuff.

**Comment by rune-opera** [comment] 2016-09-23 08:58
We (Blink) have a gperf generated case-sensitive hash for known CSS properties which are case-insensitive in the parser and existing CSSOM APIs. The input is made ascii lower-case before the lookup. It looks trivial to skip the lower-casing for new APIs.

**Comment by wilddamon** [comment] 2016-09-26 03:10
Yeah, it's not a large new code path - we'd be able to split up that function and/or have a flag to skip the lowercasing loop :)

**Comment by tabatkins** [comment] 2017-05-23 00:55
Since we don't really care which way this goes, we'll just decide it at the next meeting and be done with it.

**Comment by nainar** [comment] 2017-10-17 00:15
Closing as this was added in #445

**Closed by nainar** 2017-10-17 00:15 UTC
Labels: css-typed-om-1, Needs Edits
