### ISSUE TITLE
[css-typed-om] algorithm for coercing value doesn't describe how to check grammar

### ISSUE THREAD

**Issue by dbaron** [w3c/css-houdini-drafts#566] opened 2018-01-26 01:52 UTC
The spec describes an [algorithm that coerces value into an appropriate type for a given property](https://drafts.css-houdini.org/css-typed-om-1/#algorithm-that-coerces-value-into-an-appropriate-type-for-a-given-property).

It says:

> If value is a CSSStyleValue,
>
> If value does not match the grammar of a list-valued property iteration of property, throw a TypeError and exit this algorithm. Otherwise, return the value.

But it doesn't say how to tell if a `CSSStyleValue` matches the grammar for a list-valued property iteration of the property.

**Comment by nainar** [comment] 2018-01-29 01:39
Duplicate of #511

**Comment by dbaron** [comment] 2018-01-30 08:13
I don't think this is a duplicate.  Although the link above is broken so I'm no longer sure which text it was pointing to.  But the [normalize a style value](https://drafts.css-houdini.org/css-typed-om-1/#normalize-a-style-value) section still has the same text.  And my underling point was not confusion about the list-valued concept, but that the spec doesn't define what it means for an object tree/graph to match a grammar (which is for text).

**Comment by darrnshn** [comment] 2018-01-31 03:51
Hmm, maybe a cheap way to get around this would be to check if the _serialization_ of the object tree/graph matches the grammar? Not sure if that'll cause other problems tho. Doing this properly might require a table like in #488 ?

**Comment by tabatkins** [comment] 2018-01-31 04:03
We don't want to rely on serialization; that way lies madness.

CSSNumericValues already define a notion of "matching" a CSS grammar term - they "match" `<length>` if their type is `{length: 1}`, etc.  Handwaving somewhat, what we want is the same notion - defining that certain TypedOM values match certain grammar constructions, such that you can validate a TypedOM value against a CSS grammar same as you can a string.

**Closed** 2018-02-01 03:05 UTC
Labels: claimed, css-typed-om-1
