### ISSUE TITLE
CSSColorValue missing from TypedOM?

### ISSUE THREAD

**Issue by Snugug** [w3c/css-houdini-drafts#211] opened 2016-05-31 01:31 UTC
Reading over https://drafts.css-houdini.org/css-typed-om/, it seemed to me that CSSColorValue _should_ be a subclass of CSSStyleValue. I see it mentioned in https://github.com/w3c/css-houdini-drafts/issues/208 but not codified anywhere.

**Comment by shans** [comment] 2016-05-31 01:39
Duplicate of #159

**Closed by shans** 2016-05-31 01:39 UTC
