### ISSUE TITLE
[css-typed-om] What is CSSMathValue.type?

### ISSUE THREAD

**Issue by darrnshn** [w3c/css-houdini-drafts#492] opened 2017-10-19 07:11 UTC
I'm probably missing something here, but what is [CSSMathValue.type](https://drafts.css-houdini.org/css-typed-om-1/#dom-cssmathvalue-type)? The spec mentions what type of a CSSMathValue should be, but that type links to [CSSNumericValue.type](https://drafts.css-houdini.org/css-typed-om-1/#cssnumericvalue-type), which is a map not a string.

**Comment by tabatkins** [comment] 2017-10-19 18:22
It's a remnant of the world before we made things more complex. This seems like basically a dupe of #482, right?

**Comment by darrnshn** [comment] 2017-10-19 22:57
Ah right, does that mean we could just remove CSSMathValue.type, since it inherits CSSNumericValue's type() method?

**Comment by tabatkins** [comment] 2017-10-24 23:10
Yeah, we should.

**Comment by nainar** [comment] 2017-10-26 23:10
Fixed by #497

**Closed by nainar** 2017-10-26 23:10 UTC
Labels: css-typed-om-1, Needs Edits
