### ISSUE TITLE
[worklets] Merge the worklets spec into HTML?

### ISSUE THREAD

**Issue by domenic** [w3c/css-houdini-drafts#1000] opened 2020-08-07 15:21 UTC
https://drafts.css-houdini.org/worklets/

The worklets specification is, at this point, serving as a fairly stable piece of foundational infrastructure for other specifications. However, it's continuously impacted by cross-cutting changes in how HTML defines script fetching, event loops, agents, and globals, as well as Web IDL updates. See, for example, #467, #757, #938, #956, #958, #966, #981, #984, #992, and #998. This is because, along with service workers, worklets is the only other spec on the web platform that defines a new global environment.

Offline, @bfgeek mentioned it's hard for him to find the time to edit the specification. Given that, and the cross-cutting and foundational nature of worklet globals, would it make sense to merge the spec into the HTML Standard?

If the Houdini TF is interested in this, I'd be happy to put in the legwork of moving it over, triaging or moving open worklets issues, and sending pull requests to all the other worklet-using specs to ensure they link to the new definitions.

**Comment by AmeliaBR** [comment] 2020-08-07 18:36
I definitely agree that it makes sense to have the core definition of worklets in the same place as the definition of [web workers](https://html.spec.whatwg.org/multipage/workers.html) and the [window scope](https://html.spec.whatwg.org/multipage/window-object.html), both because it makes sense for authors trying to understand & compare, and for easy maintenance of spec updates.

(I'm not sure why those are defined in HTML, rather than in DOM, but that is at the discretion of those of you maintaining the specs!)

**Comment by domenic** [comment] 2020-09-17 15:34
Hi folks! Any progress on publishing the WD?

I also noticed that worklets is under the W3C restrictive document license, not the permissive one. That seems problematic for this effort. Is there any way to relicense it?

**Comment by arturoiam** [comment] 2020-09-17 22:56
http://167d636

**Comment by svgeesus** [comment] 2020-10-06 19:06
> Any progress on publishing the WD?

Yes, it was published on the 8 September
https://www.w3.org/TR/2020/WD-worklets-1-20200908/

**Comment by domenic** [comment] 2020-10-06 19:13
Ah, excellent. Any ideas on the licensing issue?

**Comment by svgeesus** [comment] 2020-10-06 19:16
By permissive, do you mean the software and document license? I thought CSS was using that for all specs. Yes, from the charter:

[This Working Group will use the W3C Software and Document license for all its deliverables.](https://www.w3.org/2019/10/css-wg-charter.html#licensing)

**Comment by domenic** [comment] 2020-10-06 19:39
Yes. Hmm, so what is the process for getting Worklets corrected to use that license? Currently it links to https://www.w3.org/Consortium/Legal/2015/doc-license

**Comment by frivoal** [comment] 2020-10-08 09:46
Given the charter, I believe that the fact that this document was published under the W3C Document License rather than the W3C Software and Document License is a mistake. I suspect that we just fix it by correcting the editor's draft, and then updating the TR publication as well, and that the charter's mandate for the W3C Software and Document License empowers us to do that without further ceremony.

Just to double check, @wseltzer, am I missing something?

**Comment by svgeesus** [comment] 2020-10-08 12:34
I agree with @frivoal and suspect this was a copy and paste error in bikeshed boilerplate files, so should also be fixed there.

**Comment by svgeesus** [comment] 2020-10-08 13:03
Okay [fixed on /TR](https://www.w3.org/TR/2020/WD-worklets-1-20200908/)

The bikeshed template for joint CSS and TAG publications still needs to be fixed @tabatkins I suspect that is why it used the wrong one.

**Comment by svgeesus** [comment] 2020-10-08 13:07
Looks like the problem is [here](https://github.com/tabatkins/bikeshed/blob/master/bikeshed/boilerplate/houdini/copyright.include) and applies to all Houdini specs.

change

```html
<a href="https://www.w3.org/Consortium/Legal/copyright-documents">document use</a>
```

to

```html
<a href="https://www.w3.org/Consortium/Legal/copyright-software-and-document">permissive document use</a>
```

**Comment by domenic** [comment] 2020-10-16 16:40
Worklets now exist in HTML, at https://html.spec.whatwg.org/multipage/worklets.html ! And https://github.com/w3c/css-houdini-drafts/pull/1011 works on updating this repository accordingly.

Other nice to haves, which I'll reopen this issue to track:

- Make https://drafts.css-houdini.org/worklets/ server-side redirect to https://html.spec.whatwg.org/multipage/worklets.html , instead of the client-side redirect created in https://github.com/w3c/css-houdini-drafts/pull/1011

- Make https://www.w3.org/TR/worklets-1/ redirect to https://html.spec.whatwg.org/multipage/worklets.html . (Maybe @sideshowbarker can help with that?)

**Closed** 2020-11-30 13:21 UTC
Labels: worklets-1
